site_name: Leetcode Problems - E

theme:
  name: material
  font: 
    text: Inter
    code: JetBrains Mono
  palette:
    scheme: slate
    primary: dark blue
    accent: deep purple

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details

copyright: Made by Eshaan Rawat
